In [1]:
#Agenda
#Model Building in Scikit Learn
#Representing text as numerical data
#Reading a text based dataset into pandas
#Vecotrizing our dataset
#Building and evaluating a model
#Comparing models
#Examining a model for further insight
#Practising this workflow on another dataset
#Tuning the vectorizer(discussion)



In [9]:
#Model Building in Scikit Learn
#load iris dataset as an example
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [10]:
#store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target

#Features: also known as predictors, inputs or attributes. 
#Response: also known as target, label or output
#this is the supervised learning

#Why is X capital and y small?
#X is matrix: meaning its two dimensional
#y is vector: meaning its one dimensional

#that is to be the object shapes setup in scikit 
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [13]:
#Examine first 5 rows of feature matrix (including feature)
import pandas as pd
pd.DataFrame(X, columns = iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
#Examine the response vector
print(y)
#we will get three classes 0, 1, 2
#this is a classification problem


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
#in order to build the model, features must be numericand every observation must have the same features in the same order

#Scikit learn four step model, import, instantiate, fit, predict
from sklearn.neighbors import KNeighborsClassifier

#instantiate the model (with default parameters)
knn = KNeighborsClassifier()

#fit model
knn.fit(X,y)
#In General, what happens to fit process?
#it is learning the features between features and response
#So that it can make predictions


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [16]:
#In order to make predictions, the new observations must have the same features as the training observations
#both in numbering and meaning

#it learnt from only four features, if, we are to give new observations with 5 values, it will throw error


#predict the response for new observation
knn.predict([[3, 5, 4, 2]])

array([1])

In [ ]:
#its of class 1

In [17]:
#PART 2
#Representing text as numeric
simple_train = ['call you tonight', 'Call me a cab', 'Please call me.... Please!']

In [18]:
#Text Analysis is a major application field for machine learning algorithms. However raw data, 
    #a sequence of symbols cannot be fed directly to the algorithms themselves as most of them expect
    #numerical feature vectors with a fixed size rather than the raw text documents with variable length

    #We will use CountVectorizer to convert text into matrix


In [19]:
#import and instantiate Countvectorizer (with default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [20]:
#Learn the vocabulary of trainning data (Occurs in place)
vect.fit(simple_train)
#here its learning the vocabulary of the training data

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
#examine the fitted voccabulary
vect.get_feature_names()
#because of the token pattern we see above as regular expressions
#b is the boundary character
#w word character
#w+ one or more word character

#5 interesting things it did while learning the vocabulary data, using the default vectorizer,
    #but u can change all those parameters if u want to
#it has taken away all the a
#it has taken away all the periods, exlamation, punctuation points
#make all words lower case, as its mentioned in the code
#they are now in alphabetical order
#no duplicates




['cab', 'call', 'me', 'please', 'tonight', 'you']

In [22]:
#this is going to be the fourth step,
#transform training data into a document - term matrix
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm
#Qns: why is it 3 * 6 matrix
#python is considering as rows by colns
#Documents (rows) 3 of them
#Terms (columns) 6 of them




<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [23]:
#Convert sparse matrix to a dense matrix
simple_train_dtm.toarray()
#3 rows and 6 columns

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [25]:
#Examine the vocabulary and document - term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns = vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [26]:
#this is representation of text in form of numerical
#and so far we have built 'Feature Matrix', one row per document
#using this tyoe, we are able to build model, 
#we will build model with real world data
#We needed X

#check type of document term matrix
type(simple_train_dtm)


scipy.sparse.csr.csr_matrix

In [27]:
#Examine the sparse matrix contents
print(simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [28]:
#on the left, its the cordinates of non zero values
#and on the right, its the values on that point

#example text for model testing
simple_test = ["please dont call me"]

In [ ]:
#In order to **make a prediction**, 
#the new observation must have the **same features as the training observations**, both in
#number and meaning

#in training we had 6 columns
#in testing we have only one row
#hows it possible
#we are going to transform

#transform testing data into a document - term matrix


In [31]:
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [32]:
#now examine vocabulary and document - term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns =vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

In [33]:
#Qns: what happend to the word 'dont' that we didnt see during model training?
#Qns has already answered, it dropped dont

#why is it okay to drop 'dont' for my model building perspective
#model will not answer dont
#still confused

In [ ]:
#Summary
#`vect.fit(train)` **learns the vocabulary** of the training data
#`vect.transform(train)` uses the **fitted vocabulary** to build a document-term matrix from the training data
#`vect.transform(test)` uses the **fitted vocabulary** to build a document-term matrix from the testing data 
    #(and **ignores tokens it hasnt seen before)

In [54]:
#PART 3:Reading a text - based dataset into pandas
#data is tabular separated format
sms = pd.read_csv('/Users/riteshtripathi/Desktop/Data School/sms.tsv', 
                  header = None, sep = '\t', names = ['label', 'message'])

In [55]:
sms.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [45]:
#alternative to read file into pandas from url
#url = 'https://github.com/justmarkham/pycon-2016-tutorial/blob/master/data/sms.tsv'
#sms = pd.read_table(url, header = None, names = ['label', 'message'])
#sms.head()

label message
0                                    <!DOCTYPE html>     NaN
1                                   <html lang="en">     NaN
2                                             <head>     NaN
3                             <meta charset="utf-8">     NaN
4    <link rel="dns-prefetch" href="https://githu...     NaN

In [37]:
sms.shape

(5574, 2)

In [56]:
#examine the first 10 rows
sms.head(10)

#here this is going to be our training model
#here ham is going to be our response
#its going to learn relationship between message text and response values


label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [57]:
#examine the class distribution
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [58]:
#there are 80 % hams, and 20% spams

#Now lets convert labels into numerical variables
#there are various ways, but map is the best way
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [59]:
sms.head()

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [ ]:
#remember from iris dataset
X = iris.data  # X 2 dimensional
y = iris.target # y one dimensional

In [60]:
#How to define x and y (from sms data) from countvectorize data
X = sms.message
y = sms.label_num
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [ ]:
#Why X here is one dimensional
#bse its going to be transformed to two dimesnional by countvectorized

#its always better to pass one dimensional objects to countvectorized
#if you pass more than one dimensional objects to coun...it will not understand


In [62]:
#Split X and y into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

#Qns: why should we split before vectorizing?
##what is the purpose of traintest
#for model evaluation
#you want to simulate future
#past data is exchangable for furture data(through train test)
#thats the theory, we can pretend that from our past data, is going to come into our future data
#by training, fitting, evaluating, we are going to sense how our model is going to perform

#therefore the main concept of traintest is that past data is exchangle for future data
#you will want to train your model on all the data

(4179,)
(1393,)
(4179,)
(1393,)


In [66]:
#Part 4 of the steps
#Vectorizing our dataset
#instantiate the vecotrizer
vect = CountVectorizer()

In [67]:
#learning training data vocublary, then use it
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [68]:
#equivalently: combine fit and transform into
X_train_dtm = vect.fit_transform(X_train)
#1:24:38
#this step does the same thing as of above, its a shorter code

In [69]:
#examine the document - term matrix
X_train_dtm
#here 4179 is number of rows in X train
#7456 number of tokens (can be words, sentences, etc, but here by default they are words, in this case)

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [70]:
#transform testing data(using fitted vocublary) into docuemnt - term
X_test_dtm = vect.transform(X_test)
X_test_dtm

#remember, in test, we never do fit
#we hence do only transform on testing set

#vocublary was used to learn from the training data
#the same vocublary was used when transforming testing data
#into a document term matrix


<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [ ]:
#Buidling and Evaluating a model
#The multinomial Naive Bayes classifier is suitable for classification with descrete features
#e.g: word counts for text classification

#The multinomial distribution normally requires integer feature counts. However in practice fractional counts such as 
#tf - idf may also work


In [72]:
#import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [73]:
#train the model using X_train_dtm(timing it with an Ipython magic command)
%time nb.fit(X_train_dtm, y_train)

# %time is magic command, and used it just like that


CPU times: user 7.92 ms, sys: 33.5 ms, total: 41.4 ms
Wall time: 166 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [74]:
# naive base is faster than cross fold validation and GridSearchCV
#if you got time, then apply other models too...
#in a little bit we will compare with logisitc regression



In [75]:
#make class predictionfor X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [77]:
#Claculate accuracy of class prediction
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)
#the result is obtained with default settings 

0.9885139985642498

In [78]:
#print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)
#1203 are true negatives
#174 are true positives
#5 is false positives: you falsely predcited positives, positive class is spam, bse i assigned spam as 1
    #anything you assign as 1 is called positive class, and 0 is called negative class
    #in this case, i falsely predictied spam, actually they were ham
#11, false negatives

array([[1203,    5],
       [  11,  174]])

In [80]:
#print message text for false positives (ham incorrectly classified as spam)
X_test[(y_pred_class == 1) & (y_test == 0)]

#OR

X_test[y_pred_class > y_test]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [82]:
# print message text for the false negatives (spam incorrectly classified as ham)
X_test[y_pred_class < y_test]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [83]:
#Example false negative
X_test[3132]
#to get back that value at 3132

"LookAtMe!: Thanks for your purchase of a video clip from LookAtMe!, you've been charged 35p. Think you can do better? Why not send a video in a MMSto 32323."

In [84]:
#What is the difference between false positives and false negatives
#false negatives have lot longer messages


In [86]:
#before doing the last step
#we see whats the probability of class 0 and class 1
nb.predict_proba(X_test_dtm)

array([[9.97122551e-01, 2.87744864e-03],
       [9.99981651e-01, 1.83488846e-05],
       [9.97926987e-01, 2.07301295e-03],
       ...,
       [9.99998910e-01, 1.09026171e-06],
       [1.86697467e-10, 1.00000000e+00],
       [9.99999996e-01, 3.98279868e-09]])

In [85]:
#Calculate predicted probablities for X_test_dtm (poorly calibrated)
#percentage probability of each class
#i want probabilites of class 1 here, 

y_pred_prob = nb.predict_proba(X_test_dtm)[: , 1]
y_pred_prob

#why i am doing this step, is to do model eval using AUC
#here my result is the probability of all class 1

array([2.87744864e-03, 1.83488846e-05, 2.07301295e-03, ...,
       1.09026171e-06, 1.00000000e+00, 3.98279868e-09])

In [87]:
#Calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)
#since our accuracy score was high, AUC is high too


0.9866431000536962

In [ ]:
#Part6: 
#Comparing Models
#Logistic Regression: Its a linear model for classification
#we are going to compare naive with logsitic regression
#We will compare multinomial Naive Bayes with [logistic regression]
#(http://scikit-learn.org/stable/modules/linear_model.html

#Logistic regression, despite its name, is a **linear model for classification** 
    #rather than regression. Logistic regression

In [91]:
#import and instantiate a logistic model 
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver = 'lbfgs')

In [92]:
#train model using X_train_dtm
%time logreg.fit(X_train_dtm, y_train)

CPU times: user 256 ms, sys: 121 ms, total: 377 ms
Wall time: 385 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [93]:
#make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test_dtm)

In [94]:
#Calculate predicted probabilites for X_test_dtm
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([0.00959377, 0.00295662, 0.00452424, ..., 0.031302  , 0.99748962,
       0.00119521])

In [95]:
#Calculate Accuracy
metrics.accuracy_score(y_test, y_pred_class)
#predicted probabilites in logistic regression are well calibrated than naive


0.9877961234745154

In [96]:
#Calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.9936280651512441

In [97]:
#Print 7, this section: why naive predcited ham or spam,
#kind of how naove bayes work

#Examining a model for further insight
#we will examine our tranied Naive Bayes model to calculate the approximate spamminess of each token
# store the vocabulary of X_train
X_train_tokens = vect.get_feature_names()
len(X_train_tokens)

7456

In [98]:
# examine the first 50 tokens
print(X_train_tokens[0:50])

['00', '000', '008704050406', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090201529', '07090298926', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '07786200117', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705']


In [99]:
# examine the last 50 tokens
print(X_train_tokens[-50:])

['yer', 'yes', 'yest', 'yesterday', 'yet', 'yetunde', 'yijue', 'ym', 'ymca', 'yo', 'yoga', 'yogasana', 'yor', 'yorge', 'you', 'youdoing', 'youi', 'youphone', 'your', 'youre', 'yourjob', 'yours', 'yourself', 'youwanna', 'yowifes', 'yoyyooo', 'yr', 'yrs', 'ything', 'yummmm', 'yummy', 'yun', 'yunny', 'yuo', 'yuou', 'yup', 'zac', 'zaher', 'zealand', 'zebra', 'zed', 'zeros', 'zhong', 'zindgi', 'zoe', 'zoom', 'zouk', 'zyada', 'èn', '〨ud']


In [100]:
# Naive Bayes counts the number of times each token appears in each class
#below function counts number of times each token appeared in each class
nb.feature_count_

array([[ 0.,  0.,  0., ...,  1.,  1.,  1.],
       [ 5., 23.,  2., ...,  0.,  0.,  0.]])

In [101]:
# rows represent classes, columns represent tokens
nb.feature_count_.shape

(2, 7456)

In [102]:
# number of times each token appears across all HAM messages
ham_token_count = nb.feature_count_[0, :]
ham_token_count


array([0., 0., 0., ..., 1., 1., 1.])

In [103]:
# number of times each token appears across all SPAM messages
spam_token_count = nb.feature_count_[1, :]
spam_token_count

array([ 5., 23.,  2., ...,  0.,  0.,  0.])

In [104]:
# create a DataFrame of tokens with their separate ham and spam counts
tokens = pd.DataFrame({'token':X_train_tokens, 'ham':ham_token_count, 'spam':spam_token_count}).set_index('token')
tokens.head()

ham  spam
token                  
00            0.0   5.0
000           0.0  23.0
008704050406  0.0   2.0
0121          0.0   1.0
01223585236   0.0   1.0

In [105]:
# examine 5 random DataFrame rows
tokens.sample(5, random_state=6)

ham  spam
token                   
very          64.0   2.0
nasty          1.0   1.0
villa          0.0   1.0
beloved        1.0   0.0
textoperator   0.0   2.0

In [106]:

# Naive Bayes counts the number of observations in each class
nb.class_count_
#3617 ham

array([3617.,  562.])

In [ ]:
# Before we can calculate the "spamminess" of each token, we need to avoid **dividing by zero** 
#and account for the **class imbalance**.


In [107]:
# add 1 to ham and spam counts to avoid dividing by 0
tokens['ham'] = tokens.ham + 1
tokens['spam'] = tokens.spam + 1
tokens.sample(5, random_state=6)
#here i am normalizing it


ham  spam
token                   
very          65.0   3.0
nasty          2.0   2.0
villa          1.0   2.0
beloved        2.0   1.0
textoperator   1.0   3.0

In [108]:
# convert the ham and spam counts into frequencies
tokens['ham'] = tokens.ham / nb.class_count_[0]
tokens['spam'] = tokens.spam / nb.class_count_[1]
tokens.sample(5, random_state=6)


ham      spam
token                           
very          0.017971  0.005338
nasty         0.000553  0.003559
villa         0.000276  0.003559
beloved       0.000553  0.001779
textoperator  0.000276  0.005338

In [ ]:
#above: very word, refers to 5% in spam

In [109]:
# calculate the ratio of spam-to-ham for each token
tokens['spam_ratio'] = tokens.spam / tokens.ham
tokens.sample(5, random_state=6)

ham      spam  spam_ratio
token                                       
very          0.017971  0.005338    0.297044
nasty         0.000553  0.003559    6.435943
villa         0.000276  0.003559   12.871886
beloved       0.000553  0.001779    3.217972
textoperator  0.000276  0.005338   19.307829

In [ ]:
#text operator is more spammy word if we see spam ratio, and followed by other tokens

In [110]:
# examine the DataFrame sorted above by spam_ratio
# note: use sort() instead of sort_values() for pandas 0.16.2 and earlier
tokens.sort_values('spam_ratio', ascending=False)

ham      spam  spam_ratio
token                                     
claim       0.000276  0.158363  572.798932
prize       0.000276  0.135231  489.131673
150p        0.000276  0.087189  315.361210
tone        0.000276  0.085409  308.925267
guaranteed  0.000276  0.076512  276.745552
...              ...       ...         ...
da          0.032900  0.001779    0.054084
she         0.035665  0.001779    0.049891
he          0.047000  0.001779    0.037858
lt          0.064142  0.001779    0.027741
gt          0.064971  0.001779    0.027387

[7456 rows x 3 columns]

In [ ]:
#above, the most spammy word was 'claim'
#and so on

In [111]:
# look up the spam_ratio for a given token
tokens.loc['dating', 'spam_ratio']

83.66725978647686